- ros_topic_name: /car/sprung_mass_pose
  gz_topic_name:  /car/sprung_mass_pose
  ros_type_name:  geometry_msgs/msg/PoseStamped
  gz_type_name:   gz.msgs.Pose
  direction:      ROS_TO_GZ

- ros_topic_name: /model/quarter_car/joint/chassis_joint/cmd_pos
  gz_topic_name:  /model/quarter_car/joint/chassis_joint/cmd_pos
  ros_type_name:  std_msgs/msg/Float64
  gz_type_name:   gz.msgs.Double
  direction:      ROS_TO_GZ
